### ISSUE TITLE
Some sites return "Internal Server Error" instead of html information

### ISSUE THREAD

**Issue by xiaogz** [xiaogz/onlineParser#2]
I don't know yet why some sites, like `9gag.com`,  `newgrounds.com`, and `cnn.com` return "Internal Server Error" while sites like `hotmail.com`, `reddit.com`, `wordpress.com` don't.

Will do research into this sometime soon

**Comment by oosidat** [comment]
That might the the app returning an Internal Service Error (500) and not the site.

**Comment by xiaogz** [comment]
What could be the reasons for the app to work for certain sites and not others? It seems kinda random to me

**Comment by oosidat** [comment]
Put a try catch around it, and display the error message in the response.

Also check if those sites work locally.

**Comment by xiaogz** [comment]
Figured out why some sites are giving this app problems: I mistakenly assumed that every site uses `<meta name='description' content='...'>` but cnn.com (and some others) uses `content='...' property='og:description'`

**Comment by xiaogz** [comment]
Figured out that the problem was due to open-uri not allowing redirects; I thus added a gem (open_uri_redirection) and allowed safe redirections only (from http to https)
